#ifndef LIBNEWTONSOFTJSON_GLOBAL_H
#define LIBNEWTONSOFTJSON_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(LIBNEWTONSOFTJSON_LIBRARY)
#  define LIBNEWTONSOFTJSONSHARED_EXPORT Q_DECL_EXPORT
#else
#  define LIBNEWTONSOFTJSONSHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // LIBNEWTONSOFTJSON_GLOBAL_H
