#ifndef QTHREADMANAGER_GLOBAL_H
#define QTHREADMANAGER_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(QTHREADMANAGER_LIBRARY)
#  define QTHREADMANAGERSHARED_EXPORT Q_DECL_EXPORT
#else
#  define QTHREADMANAGERSHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // QTHREADMANAGER_GLOBAL_H
